export const CHANGE_SIZE_BRUSH = 'CHANGE_SIZE_BRUSH';
export const CHANGE_COLOR_BRUSH = 'CHANGE_COLOR_BRUSH';
export const TOGGLE_BRUSH_MENU = 'TOGGLE_BRUSH_MENU';
export const CLEAR_TRUE = 'CLEAR_TRUE';
export const CLEAR_FALSE = 'CLEAR_FALSE';
